server:
  port: 8091
  
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0 #默认零号数据库
    password: siping #链接密码
    timeout: 3000  # 链接超时时间.
    pool: 
      max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
      min-idle: 0  # 最小的空闲链接数.
      max-idle: 8  # 最大的空闲链接.
      max-wait: 3000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/electric_v1?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 15
logging:
  level:
    com:
      ele:
        mapper: debug

# netty配置
netty:
  # 端口号
  port: 12345
  # 最大线程数
  maxThreads: 1024
  # 数据包的最大长度
  max_frame_length: 65535

